export const ActionTypes = {
  SET_PRODUCTS: "SET_PRODUCTS",
  FILTER_PRODUCTS: "FILTER_PRODUCTS",
  SELECT_PRODUCT: "SELECT_PRODUCT",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",

  ADD_TO_CART: "ADD_TO_CART,",
  INCREASE_QTY: "INCREASE_QTY",
  DECREASE_QTY: "DECREASE_QTY",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
  RESET_FILTER: "RESET_FILTER",
};
